### PR TITLE
Feature/eco 3742/add payment js auth

### PR DESCRIPTION
**Pull request by pyvovarov-s**

### CODE REVIEW

**Comment by dereuromark** [comment]
Never add labels yourself, always let me (and release app) do that.

**Comment by pyvovarov-s** [comment]
> Never add labels yourself, always let me (and release app) do that.

but there is no any label.

**Comment by dereuromark** [comment]
Someone added them to repo itself, I had to remove them as they were invalid.

**Comment by dereuromark** [comment]
Instead please hook in the Spryker CI at some point then (once it targets master!).

**Comment by pyvovarov-s** [comment]
> Someone added them to repo itself, I had to remove them as they were invalid.

I just wondering who can add any label to this repo also I don't see that any labels were added to repo (the  history is clean)

**Comment by dereuromark** [comment]
Is this repo dead?

**Pull request closed without merging**
